import type { Capability, FreeTierClass } from './contracts.js';

export interface ProviderPreset {
  id: string;
  name: string;
  adapterType: 'openai-compatible' | 'gemini';
  baseUrl: string;
  apiKeyUrl: string;
  website: string;
  category: 'free' | 'freemium' | 'local' | 'commercial';
  descriptionEn: string;
  descriptionVi: string;
  keyInstructionsEn: string;
  keyInstructionsVi: string;
  seedModels: Array<{
    modelId: string;
    capabilities: Capability[];
    freeTier: FreeTierClass;
    priority?: number;
  }>;
}

/**
 * Curated provider catalog synthesized from OmniRoute (349 providers), 9router, and FreeLLMAPI.
 * Features 70+ providers organized into:
 * 1. Free / Freemium / Local (prioritized on top)
 * 2. Commercial / Pay-as-you-go (classified underneath)
 */
export const PROVIDER_PRESETS: ProviderPreset[] = [
  // ==========================================
  // 1. FREE / FREEMIUM / LOCAL TIER PROVIDERS
  // ==========================================
  {
    id: 'openrouter',
    name: 'OpenRouter',
    adapterType: 'openai-compatible',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKeyUrl: 'https://openrouter.ai/keys',
    website: 'https://openrouter.ai',
    category: 'free',
    descriptionEn: 'Aggregator with dozens of recurring zero-credit free models (:free suffix).',
    descriptionVi: 'Cổng tổng hợp với hàng chục model miễn phí 0đ định kỳ (hậu tố :free).',
    keyInstructionsEn: 'Create a free account, generate an API key with $0 balance.',
    keyInstructionsVi: 'Tạo tài khoản miễn phí, tạo API key không cần nạp tiền.',
    seedModels: [
      { modelId: 'google/gemini-2.0-flash-exp:free', capabilities: ['chat', 'streaming', 'tools', 'vision'], freeTier: 'free_verified', priority: 100 },
      { modelId: 'deepseek/deepseek-r1:free', capabilities: ['chat', 'streaming'], freeTier: 'free_verified', priority: 95 },
      { modelId: 'meta-llama/llama-3.3-70b-instruct:free', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 90 },
      { modelId: 'qwen/qwen-2.5-coder-32b-instruct:free', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 90 },
      { modelId: 'mistralai/mistral-small-24b-instruct-2501:free', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 85 },
    ],
  },
  {
    id: 'groq',
    name: 'Groq',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.groq.com/openai/v1',
    apiKeyUrl: 'https://console.groq.com/keys',
    website: 'https://groq.com',
    category: 'free',
    descriptionEn: 'Ultra-fast LPU inference (500+ tok/s) with generous recurring free limits.',
    descriptionVi: 'Tốc độ siêu nhanh với chip LPU (500+ tok/s), hạn ngạch miễn phí dồi dào.',
    keyInstructionsEn: 'Sign in to Groq Console and create an API Key (no credit card needed).',
    keyInstructionsVi: 'Đăng nhập Groq Console và tạo API Key (không cần thẻ tín dụng).',
    seedModels: [
      { modelId: 'llama-3.3-70b-versatile', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 95 },
      { modelId: 'llama-3.1-8b-instant', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 90 },
      { modelId: 'mixtral-8x7b-32768', capabilities: ['chat', 'streaming'], freeTier: 'free_verified', priority: 80 },
    ],
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    adapterType: 'gemini',
    baseUrl: 'https://generativelanguage.googleapis.com',
    apiKeyUrl: 'https://aistudio.google.com/app/apikey',
    website: 'https://aistudio.google.com',
    category: 'free',
    descriptionEn: 'Official Google AI Studio free tier: 15 RPM, 1M+ token context window.',
    descriptionVi: 'Gói miễn phí chính thức từ Google AI Studio: 15 RPM, ngữ cảnh 1M+ tokens.',
    keyInstructionsEn: 'Sign in with Google account at Google AI Studio and click "Create API key".',
    keyInstructionsVi: 'Đăng nhập bằng tài khoản Google tại Google AI Studio và nhấn "Create API key".',
    seedModels: [
      { modelId: 'gemini-2.5-flash', capabilities: ['chat', 'streaming', 'tools', 'vision'], freeTier: 'free_verified', priority: 98 },
      { modelId: 'gemini-2.0-flash', capabilities: ['chat', 'streaming', 'tools', 'vision'], freeTier: 'free_verified', priority: 95 },
      { modelId: 'gemini-1.5-flash', capabilities: ['chat', 'streaming', 'tools', 'vision'], freeTier: 'free_verified', priority: 85 },
    ],
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.cerebras.ai/v1',
    apiKeyUrl: 'https://cloud.cerebras.ai/platform',
    website: 'https://www.cerebras.ai',
    category: 'free',
    descriptionEn: 'World-record speed inference (1800+ tok/s) with free developer tier.',
    descriptionVi: 'Tốc độ kỷ lục thế giới (1800+ tok/s) với gói miễn phí cho lập trình viên.',
    keyInstructionsEn: 'Sign up on Cerebras Cloud, verify email, and generate an API key.',
    keyInstructionsVi: 'Đăng ký trên Cerebras Cloud, xác thực email và tạo API key.',
    seedModels: [
      { modelId: 'llama-3.3-70b', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 92 },
      { modelId: 'llama-3.1-8b', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 88 },
      { modelId: 'qwen-3-32b', capabilities: ['chat', 'streaming'], freeTier: 'free_verified', priority: 85 },
    ],
  },
  {
    id: 'github',
    name: 'GitHub Models',
    adapterType: 'openai-compatible',
    baseUrl: 'https://models.github.ai/inference',
    apiKeyUrl: 'https://github.com/settings/tokens',
    website: 'https://github.com/marketplace/models',
    category: 'free',
    descriptionEn: 'Free Azure AI / OpenAI access (GPT-4o, Llama 3.3) for GitHub accounts.',
    descriptionVi: 'Truy cập GPT-4o, Llama 3.3 miễn phí qua GitHub Personal Access Token.',
    keyInstructionsEn: 'Generate a classic GitHub token (no specific scopes required for Models).',
    keyInstructionsVi: 'Tạo GitHub Personal Access Token (không cần chọn quyền đặc biệt nào).',
    seedModels: [
      { modelId: 'gpt-4o', capabilities: ['chat', 'streaming', 'tools', 'vision'], freeTier: 'free_verified', priority: 94 },
      { modelId: 'gpt-4o-mini', capabilities: ['chat', 'streaming', 'tools', 'vision'], freeTier: 'free_verified', priority: 90 },
      { modelId: 'Meta-Llama-3.3-70B-Instruct', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 88 },
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.mistral.ai/v1',
    apiKeyUrl: 'https://console.mistral.ai/api-keys/',
    website: 'https://mistral.ai',
    category: 'free',
    descriptionEn: 'La Plateforme free experimentation tier: Codestral, Mistral Small/Nemo.',
    descriptionVi: 'Gói thử nghiệm miễn phí La Plateforme: Codestral, Mistral Small/Nemo.',
    keyInstructionsEn: 'Create an account on console.mistral.ai and generate an API key.',
    keyInstructionsVi: 'Đăng ký tại console.mistral.ai và tạo API key trong mục API Keys.',
    seedModels: [
      { modelId: 'codestral-latest', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 92 },
      { modelId: 'mistral-small-latest', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 85 },
    ],
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.siliconflow.cn/v1',
    apiKeyUrl: 'https://cloud.siliconflow.cn/account/ak',
    website: 'https://siliconflow.cn',
    category: 'free',
    descriptionEn: 'High-speed cloud inference with generous free credits & free DeepSeek/Qwen models.',
    descriptionVi: 'Nền tảng suy luận đám mây tốc độ cao với các model DeepSeek, Qwen miễn phí.',
    keyInstructionsEn: 'Sign up on SiliconFlow Cloud and copy your API key.',
    keyInstructionsVi: 'Đăng ký trên SiliconFlow Cloud và sao chép API key trong trang quản trị.',
    seedModels: [
      { modelId: 'deepseek-ai/DeepSeek-V3', capabilities: ['chat', 'streaming'], freeTier: 'free_verified', priority: 92 },
      { modelId: 'Qwen/Qwen2.5-72B-Instruct', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 90 },
      { modelId: 'deepseek-ai/DeepSeek-R1', capabilities: ['chat', 'streaming'], freeTier: 'free_verified', priority: 88 },
    ],
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api-inference.huggingface.co/v1',
    apiKeyUrl: 'https://huggingface.co/settings/tokens',
    website: 'https://huggingface.co',
    category: 'free',
    descriptionEn: 'Serverless Inference API supporting thousands of open-source models for free.',
    descriptionVi: 'API suy luận serverless hỗ trợ hàng ngàn model mã nguồn mở miễn phí.',
    keyInstructionsEn: 'Create a Hugging Face User Access Token with read permissions.',
    keyInstructionsVi: 'Tạo Access Token với quyền đọc tại mục Settings -> Access Tokens.',
    seedModels: [
      { modelId: 'meta-llama/Llama-3.2-3B-Instruct', capabilities: ['chat', 'streaming'], freeTier: 'free_verified', priority: 80 },
      { modelId: 'Qwen/Qwen2.5-Coder-32B-Instruct', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 85 },
    ],
  },
  {
    id: 'cohere',
    name: 'Cohere',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.cohere.com/v1',
    apiKeyUrl: 'https://dashboard.cohere.com/api-keys',
    website: 'https://cohere.com',
    category: 'free',
    descriptionEn: 'Free Trial Key: Command R and Command R+ models for evaluation.',
    descriptionVi: 'Key thử nghiệm miễn phí: trải nghiệm model Command R và Command R+.',
    keyInstructionsEn: 'Sign up at Cohere Dashboard and generate a Free Trial API key.',
    keyInstructionsVi: 'Đăng ký tại Cohere Dashboard và lấy Free Trial API key.',
    seedModels: [
      { modelId: 'command-r-plus-08-2024', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 88 },
      { modelId: 'command-r-08-2024', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 82 },
    ],
  },
  {
    id: 'sambanova',
    name: 'SambaNova Cloud',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.sambanova.ai/v1',
    apiKeyUrl: 'https://cloud.sambanova.ai/apis',
    website: 'https://sambanova.ai',
    category: 'free',
    descriptionEn: 'Ultra-fast SN40L chip inference with high rate limits for Llama 3.3 and Qwen.',
    descriptionVi: 'Suy luận siêu tốc trên chip SambaNova SN40L với hạn mức cao cho Llama 3.3.',
    keyInstructionsEn: 'Create an account on SambaNova Cloud and obtain your API key.',
    keyInstructionsVi: 'Đăng ký tài khoản trên SambaNova Cloud và tạo API key.',
    seedModels: [
      { modelId: 'Meta-Llama-3.3-70B-Instruct', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 91 },
      { modelId: 'Qwen2.5-72B-Instruct', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 89 },
    ],
  },
  {
    id: 'hyperbolic',
    name: 'Hyperbolic',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.hyperbolic.xyz/v1',
    apiKeyUrl: 'https://app.hyperbolic.xyz/settings',
    website: 'https://hyperbolic.xyz',
    category: 'free',
    descriptionEn: 'Decentralized GPU cloud offering free tier access for DeepSeek and Llama models.',
    descriptionVi: 'Nền tảng GPU phi tập trung cung cấp gói miễn phí cho DeepSeek và Llama.',
    keyInstructionsEn: 'Register on Hyperbolic and generate an API key.',
    keyInstructionsVi: 'Đăng ký trên Hyperbolic và tạo API key trong phần cài đặt.',
    seedModels: [
      { modelId: 'deepseek-ai/DeepSeek-V3', capabilities: ['chat', 'streaming'], freeTier: 'free_verified', priority: 89 },
      { modelId: 'meta-llama/Meta-Llama-3.1-70B-Instruct', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 87 },
    ],
  },
  {
    id: 'nvidia',
    name: 'NVIDIA NIM',
    adapterType: 'openai-compatible',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    apiKeyUrl: 'https://build.nvidia.com/explore/discover',
    website: 'https://build.nvidia.com',
    category: 'free',
    descriptionEn: 'NVIDIA API Catalog: 1000 free credits upon signup for accelerated models.',
    descriptionVi: 'Danh mục NVIDIA API: tặng 1000 credits miễn phí khi đăng ký cho các model tối ưu hóa.',
    keyInstructionsEn: 'Log in with NVIDIA account at build.nvidia.com and generate a personal API key.',
    keyInstructionsVi: 'Đăng nhập tài khoản NVIDIA tại build.nvidia.com và tạo personal API key.',
    seedModels: [
      { modelId: 'meta/llama-3.3-70b-instruct', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 93 },
      { modelId: 'deepseek-ai/deepseek-r1', capabilities: ['chat', 'streaming'], freeTier: 'free_verified', priority: 90 },
    ],
  },
  {
    id: 'cloudflare-ai',
    name: 'Cloudflare Workers AI',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1',
    apiKeyUrl: 'https://dash.cloudflare.com/profile/api-tokens',
    website: 'https://developers.cloudflare.com/workers-ai/',
    category: 'free',
    descriptionEn: 'Daily free allocation of Neurons for serverless inference at the edge.',
    descriptionVi: 'Hạn mức Neurons miễn phí hàng ngày để chạy mô hình AI tại rìa mạng toàn cầu.',
    keyInstructionsEn: 'Create an API Token with Workers AI Read/Write permissions.',
    keyInstructionsVi: 'Tạo API Token có quyền Workers AI trong Cloudflare Dashboard.',
    seedModels: [
      { modelId: '@cf/meta/llama-3.3-70b-instruct-fp8-fast', capabilities: ['chat', 'streaming'], freeTier: 'free_verified', priority: 86 },
      { modelId: '@cf/meta/llama-3.1-8b-instruct', capabilities: ['chat', 'streaming'], freeTier: 'free_verified', priority: 82 },
    ],
  },
  {
    id: 'opencode',
    name: 'OpenCode Free',
    adapterType: 'openai-compatible',
    baseUrl: 'https://opencode.ai/v1',
    apiKeyUrl: 'https://opencode.ai',
    website: 'https://opencode.ai',
    category: 'free',
    descriptionEn: 'No-auth public coding and chat endpoint provided by OpenCode community.',
    descriptionVi: 'Endpoint miễn phí không cần API key cho lập trình và chat từ cộng đồng OpenCode.',
    keyInstructionsEn: 'No API key needed (use any dummy string).',
    keyInstructionsVi: 'Không cần API key (nhập chuỗi bất kỳ).',
    seedModels: [
      { modelId: 'opencode/qwen-2.5-coder-32b', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 85 },
    ],
  },
  {
    id: 'deepinfra',
    name: 'DeepInfra',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.deepinfra.com/v1/openai',
    apiKeyUrl: 'https://deepinfra.com/dash/api_keys',
    website: 'https://deepinfra.com',
    category: 'freemium',
    descriptionEn: 'Cost-effective serverless inference with initial free testing credits.',
    descriptionVi: 'Hạ tầng serverless giá rẻ với gói dùng thử ban đầu cho các model mã nguồn mở.',
    keyInstructionsEn: 'Sign up with GitHub at DeepInfra and copy your API key.',
    keyInstructionsVi: 'Đăng nhập qua GitHub tại DeepInfra và sao chép API key.',
    seedModels: [
      { modelId: 'meta-llama/Meta-Llama-3.3-70B-Instruct', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_unverified', priority: 84 },
    ],
  },
  {
    id: 'together',
    name: 'Together AI',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.together.xyz/v1',
    apiKeyUrl: 'https://api.together.xyz/settings/api-keys',
    website: 'https://together.ai',
    category: 'freemium',
    descriptionEn: 'Fast open-source model inference platform with free credits on signup.',
    descriptionVi: 'Nền tảng suy luận model mở cực nhanh với credits miễn phí khi tạo tài khoản.',
    keyInstructionsEn: 'Sign up on Together AI and grab your API key from settings.',
    keyInstructionsVi: 'Đăng ký tại Together AI và lấy API key trong Settings.',
    seedModels: [
      { modelId: 'meta-llama/Llama-3.3-70B-Instruct-Turbo', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_unverified', priority: 88 },
    ],
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    apiKeyUrl: 'https://fireworks.ai/api-keys',
    website: 'https://fireworks.ai',
    category: 'freemium',
    descriptionEn: 'Low-latency speculative inference with initial developer credits.',
    descriptionVi: 'Tốc độ phản hồi cực nhanh với công nghệ speculative decoding và credits thử nghiệm.',
    keyInstructionsEn: 'Create an account on fireworks.ai and obtain an API key.',
    keyInstructionsVi: 'Tạo tài khoản tại fireworks.ai và lấy API key.',
    seedModels: [
      { modelId: 'accounts/fireworks/models/llama-v3p3-70b-instruct', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_unverified', priority: 87 },
    ],
  },
  {
    id: 'lepton',
    name: 'Lepton AI',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.lepton.ai/v1',
    apiKeyUrl: 'https://dashboard.lepton.ai/workspace/api-keys',
    website: 'https://lepton.ai',
    category: 'freemium',
    descriptionEn: 'Cloud AI platform with free tier credits for Llama and Qwen models.',
    descriptionVi: 'Nền tảng AI đám mây với credits dùng thử cho các model phổ biến.',
    keyInstructionsEn: 'Sign up on Lepton AI dashboard and create an API token.',
    keyInstructionsVi: 'Đăng ký tại Lepton AI dashboard và tạo API token.',
    seedModels: [
      { modelId: 'llama3-3-70b', capabilities: ['chat', 'streaming'], freeTier: 'free_unverified', priority: 82 },
    ],
  },
  {
    id: 'novita',
    name: 'Novita AI',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.novita.ai/v1',
    apiKeyUrl: 'https://novita.ai/dashboard/key',
    website: 'https://novita.ai',
    category: 'freemium',
    descriptionEn: 'AI inference API platform with competitive pricing and trial tier.',
    descriptionVi: 'Nền tảng API suy luận với chi phí tối ưu và gói dùng thử.',
    keyInstructionsEn: 'Create a key in Novita AI dashboard.',
    keyInstructionsVi: 'Tạo key trong Novita AI dashboard.',
    seedModels: [
      { modelId: 'meta-llama/llama-3.3-70b-instruct', capabilities: ['chat', 'streaming'], freeTier: 'free_unverified', priority: 80 },
    ],
  },
  {
    id: 'api-airforce',
    name: 'API Airforce',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.airforce/v1',
    apiKeyUrl: 'https://api.airforce',
    website: 'https://api.airforce',
    category: 'free',
    descriptionEn: 'Community API gateway with generous free tiers for multiple open-source models.',
    descriptionVi: 'Cổng API cộng đồng với nhiều model miễn phí phong phú.',
    keyInstructionsEn: 'Obtain key from Airforce Discord or official web portal.',
    keyInstructionsVi: 'Lấy key từ cổng thông tin hoặc Discord của Airforce.',
    seedModels: [
      { modelId: 'llama-3.3-70b', capabilities: ['chat', 'streaming'], freeTier: 'free_verified', priority: 83 },
    ],
  },
  {
    id: 'arcee-ai',
    name: 'Arcee AI',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.arcee.ai/v1',
    apiKeyUrl: 'https://app.arcee.ai/settings',
    website: 'https://arcee.ai',
    category: 'freemium',
    descriptionEn: 'Specialized Small Language Models (SLMs) with free trial credits.',
    descriptionVi: 'Các mô hình ngôn ngữ chuyên biệt hiệu năng cao với gói thử nghiệm.',
    keyInstructionsEn: 'Register on Arcee AI and generate an API key.',
    keyInstructionsVi: 'Đăng ký tại Arcee AI và tạo API key.',
    seedModels: [
      { modelId: 'arcee-agent', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_unverified', priority: 81 },
    ],
  },
  {
    id: 'bytez',
    name: 'Bytez',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.bytez.com/v1',
    apiKeyUrl: 'https://bytez.com/dashboard',
    website: 'https://bytez.com',
    category: 'freemium',
    descriptionEn: 'Model hub and inference API for modern open-weights LLMs.',
    descriptionVi: 'Kho model và API suy luận cho các mô hình trọng số mở hiện đại.',
    keyInstructionsEn: 'Generate an API key in Bytez dashboard.',
    keyInstructionsVi: 'Tạo API key tại Bytez dashboard.',
    seedModels: [
      { modelId: 'meta-llama/Meta-Llama-3.1-8B-Instruct', capabilities: ['chat', 'streaming'], freeTier: 'free_unverified', priority: 79 },
    ],
  },
  {
    id: 'ollama',
    name: 'Ollama Local',
    adapterType: 'openai-compatible',
    baseUrl: 'http://127.0.0.1:11434/v1',
    apiKeyUrl: 'https://ollama.com',
    website: 'https://ollama.com',
    category: 'local',
    descriptionEn: 'Run LLMs completely offline on your local machine with zero telemetry.',
    descriptionVi: 'Chạy mô hình hoàn toàn offline trên máy tính của bạn, bảo mật tuyệt đối.',
    keyInstructionsEn: 'No API key needed. Install Ollama and run: ollama run llama3.2',
    keyInstructionsVi: 'Không cần key. Cài Ollama và chạy: ollama run llama3.2',
    seedModels: [
      { modelId: 'llama3.2', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 85 },
      { modelId: 'qwen2.5-coder', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 85 },
      { modelId: 'deepseek-r1:8b', capabilities: ['chat', 'streaming'], freeTier: 'free_verified', priority: 85 },
    ],
  },
  {
    id: 'lmstudio',
    name: 'LM Studio',
    adapterType: 'openai-compatible',
    baseUrl: 'http://127.0.0.1:1234/v1',
    apiKeyUrl: 'https://lmstudio.ai',
    website: 'https://lmstudio.ai',
    category: 'local',
    descriptionEn: 'Run local LLMs with an intuitive GUI and OpenAI-compatible local server.',
    descriptionVi: 'Chạy LLM cục bộ với giao diện trực quan và server OpenAI cục bộ.',
    keyInstructionsEn: 'No API key needed. Start the local server inside LM Studio app.',
    keyInstructionsVi: 'Không cần key. Bật Local Server trong ứng dụng LM Studio.',
    seedModels: [
      { modelId: 'local-model', capabilities: ['chat', 'streaming'], freeTier: 'free_verified', priority: 80 },
    ],
  },
  {
    id: 'vllm',
    name: 'vLLM Local / Self-Hosted',
    adapterType: 'openai-compatible',
    baseUrl: 'http://127.0.0.1:8000/v1',
    apiKeyUrl: 'https://github.com/vllm-project/vllm',
    website: 'https://vllm.ai',
    category: 'local',
    descriptionEn: 'High-throughput LLM serving engine running on local GPU or server.',
    descriptionVi: 'Engine phục vụ LLM thông lượng cao trên GPU máy cá nhân hoặc máy chủ.',
    keyInstructionsEn: 'Use your configured local vLLM API key or leave blank.',
    keyInstructionsVi: 'Sử dụng API key bạn đã cấu hình khi khởi động vLLM hoặc để trống.',
    seedModels: [
      { modelId: 'vllm-default', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'free_verified', priority: 85 },
    ],
  },

  // ==========================================
  // 2. COMMERCIAL / PAY-AS-YOU-GO PROVIDERS
  // ==========================================
  {
    id: 'openai',
    name: 'OpenAI',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.openai.com/v1',
    apiKeyUrl: 'https://platform.openai.com/api-keys',
    website: 'https://openai.com',
    category: 'commercial',
    descriptionEn: 'Industry standard: GPT-4o, GPT-4.5, o1, and o3 reasoning models.',
    descriptionVi: 'Chuẩn công nghiệp: GPT-4o, GPT-4.5 cùng các mô hình tư duy o1, o3.',
    keyInstructionsEn: 'Create an API key in the OpenAI developer platform dashboard.',
    keyInstructionsVi: 'Tạo API key trong trang quản lý lập trình viên của OpenAI.',
    seedModels: [
      { modelId: 'gpt-4o', capabilities: ['chat', 'streaming', 'tools', 'vision'], freeTier: 'paid', priority: 95 },
      { modelId: 'gpt-4o-mini', capabilities: ['chat', 'streaming', 'tools', 'vision'], freeTier: 'paid', priority: 92 },
      { modelId: 'o3-mini', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'paid', priority: 90 },
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.anthropic.com/v1',
    apiKeyUrl: 'https://console.anthropic.com/settings/keys',
    website: 'https://anthropic.com',
    category: 'commercial',
    descriptionEn: 'Claude 3.7 Sonnet (Hybrid Reasoning), Claude 3.5 Sonnet, Claude 3.5 Haiku.',
    descriptionVi: 'Claude 3.7 Sonnet (Tư duy kết hợp), Claude 3.5 Sonnet, Claude 3.5 Haiku đỉnh cao.',
    keyInstructionsEn: 'Generate an API key in the Anthropic Console.',
    keyInstructionsVi: 'Tạo API key trong bảng điều khiển Anthropic Console.',
    seedModels: [
      { modelId: 'claude-3-7-sonnet-latest', capabilities: ['chat', 'streaming', 'tools', 'vision'], freeTier: 'paid', priority: 99 },
      { modelId: 'claude-3-5-sonnet-latest', capabilities: ['chat', 'streaming', 'tools', 'vision'], freeTier: 'paid', priority: 98 },
      { modelId: 'claude-3-5-haiku-latest', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'paid', priority: 93 },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek Official',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.deepseek.com/v1',
    apiKeyUrl: 'https://platform.deepseek.com/api_keys',
    website: 'https://deepseek.com',
    category: 'commercial',
    descriptionEn: 'DeepSeek V3 and DeepSeek R1 reasoning models with ultra-low token pricing.',
    descriptionVi: 'Mô hình DeepSeek V3 và R1 chính hãng với mức chi phí token siêu rẻ.',
    keyInstructionsEn: 'Register on platform.deepseek.com and create an API key.',
    keyInstructionsVi: 'Đăng ký tại platform.deepseek.com và tạo API key trong bảng điều khiển.',
    seedModels: [
      { modelId: 'deepseek-chat', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'paid', priority: 96 },
      { modelId: 'deepseek-reasoner', capabilities: ['chat', 'streaming'], freeTier: 'paid', priority: 96 },
    ],
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.x.ai/v1',
    apiKeyUrl: 'https://console.x.ai',
    website: 'https://x.ai',
    category: 'commercial',
    descriptionEn: 'Grok 2 and Grok 2 Vision with real-time world knowledge.',
    descriptionVi: 'Mô hình Grok 2 và Grok 2 Vision với khả năng nắm bắt dữ liệu thực tế nhanh chóng.',
    keyInstructionsEn: 'Create an API key in the xAI developer console.',
    keyInstructionsVi: 'Tạo API key trong bảng điều khiển lập trình viên xAI Console.',
    seedModels: [
      { modelId: 'grok-2-latest', capabilities: ['chat', 'streaming', 'tools', 'vision'], freeTier: 'paid', priority: 94 },
      { modelId: 'grok-2-vision-latest', capabilities: ['chat', 'streaming', 'tools', 'vision'], freeTier: 'paid', priority: 92 },
    ],
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.perplexity.ai',
    apiKeyUrl: 'https://www.perplexity.ai/settings/api',
    website: 'https://perplexity.ai',
    category: 'commercial',
    descriptionEn: 'Online search-augmented models: Sonar, Sonar Pro, and Sonar Reasoning.',
    descriptionVi: 'Mô hình tích hợp tìm kiếm trực tuyến theo thời gian thực: Sonar, Sonar Pro.',
    keyInstructionsEn: 'Sign in to Perplexity and generate an API key in Settings -> API.',
    keyInstructionsVi: 'Đăng nhập Perplexity và tạo API key trong phần Settings -> API.',
    seedModels: [
      { modelId: 'sonar-pro', capabilities: ['chat', 'streaming'], freeTier: 'paid', priority: 93 },
      { modelId: 'sonar', capabilities: ['chat', 'streaming'], freeTier: 'paid', priority: 89 },
    ],
  },
  {
    id: 'moonshot',
    name: 'Moonshot AI (Kimi)',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.moonshot.cn/v1',
    apiKeyUrl: 'https://platform.moonshot.cn/console/api-keys',
    website: 'https://moonshot.cn',
    category: 'commercial',
    descriptionEn: 'Kimi Moonshot models with massive context windows (up to 2M tokens).',
    descriptionVi: 'Mô hình Kimi với ngữ cảnh khổng lồ lên tới 2 triệu tokens, xử lý tài liệu lớn.',
    keyInstructionsEn: 'Create an API key on Moonshot Open Platform.',
    keyInstructionsVi: 'Tạo API key trên Nền tảng mở Moonshot.',
    seedModels: [
      { modelId: 'moonshot-v1-128k', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'paid', priority: 91 },
      { modelId: 'moonshot-v1-32k', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'paid', priority: 88 },
    ],
  },
  {
    id: 'zhipu',
    name: 'Zhipu AI (GLM)',
    adapterType: 'openai-compatible',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    apiKeyUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
    website: 'https://zhipuai.cn',
    category: 'commercial',
    descriptionEn: 'GLM-4 Plus, GLM-4 Flash, and GLM-4V multimodal models.',
    descriptionVi: 'Mô hình GLM-4 Plus, GLM-4 Flash và đa phương tiện GLM-4V của Zhipu.',
    keyInstructionsEn: 'Sign up on BigModel platform and generate an API key.',
    keyInstructionsVi: 'Đăng ký tại nền tảng BigModel và tạo API key trong trung tâm người dùng.',
    seedModels: [
      { modelId: 'glm-4-plus', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'paid', priority: 90 },
      { modelId: 'glm-4-flash', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'paid', priority: 88 },
    ],
  },
  {
    id: 'dashscope',
    name: 'Alibaba Cloud (DashScope / Qwen)',
    adapterType: 'openai-compatible',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    apiKeyUrl: 'https://dashscope.console.aliyun.com/apiKey',
    website: 'https://www.aliyun.com',
    category: 'commercial',
    descriptionEn: 'Flagship Qwen 2.5 series (Max, Plus, Turbo, Coder) via Alibaba Cloud.',
    descriptionVi: 'Bộ mô hình Qwen 2.5 đỉnh cao (Max, Plus, Coder) qua Alibaba DashScope.',
    keyInstructionsEn: 'Activate DashScope service on Alibaba Cloud and create an API key.',
    keyInstructionsVi: 'Kích hoạt dịch vụ DashScope trên Alibaba Cloud và lấy API key.',
    seedModels: [
      { modelId: 'qwen-max', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'paid', priority: 94 },
      { modelId: 'qwen-plus', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'paid', priority: 91 },
      { modelId: 'qwen-turbo', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'paid', priority: 87 },
    ],
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.minimax.chat/v1',
    apiKeyUrl: 'https://platform.minimaxi.com/user-center/basic-information/interface-key',
    website: 'https://minimaxi.com',
    category: 'commercial',
    descriptionEn: 'MiniMax MiniMax-01 and abab6.5 series with rich reasoning and audio capabilities.',
    descriptionVi: 'Dòng mô hình MiniMax-01 và abab6.5 với năng lực hội thoại và tư duy mạnh mẽ.',
    keyInstructionsEn: 'Create an API key in the MiniMax open platform.',
    keyInstructionsVi: 'Tạo API key tại trang quản trị nền tảng MiniMax.',
    seedModels: [
      { modelId: 'MiniMax-Text-01', capabilities: ['chat', 'streaming'], freeTier: 'paid', priority: 89 },
    ],
  },
  {
    id: 'byteplus',
    name: 'BytePlus (Volcengine / Doubao)',
    adapterType: 'openai-compatible',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    apiKeyUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey',
    website: 'https://www.byteplus.com',
    category: 'commercial',
    descriptionEn: 'Doubao / Skylark models powering ByteDance ecosystem at scale.',
    descriptionVi: 'Mô hình Doubao phục vụ hệ sinh thái ByteDance với thông lượng lớn.',
    keyInstructionsEn: 'Create an API key in Volcengine Ark Console.',
    keyInstructionsVi: 'Tạo API key trong bảng điều khiển Ark của Volcengine.',
    seedModels: [
      { modelId: 'doubao-pro-32k', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'paid', priority: 89 },
    ],
  },
  {
    id: 'baichuan',
    name: 'Baichuan AI',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.baichuan-ai.com/v1',
    apiKeyUrl: 'https://platform.baichuan-ai.com/console/apikey',
    website: 'https://baichuan-ai.com',
    category: 'commercial',
    descriptionEn: 'Baichuan 4 models optimized for knowledge retrieval and Chinese language.',
    descriptionVi: 'Mô hình Baichuan 4 tối ưu hóa cho truy vấn kiến thức và ngôn ngữ châu Á.',
    keyInstructionsEn: 'Create key on Baichuan developer portal.',
    keyInstructionsVi: 'Tạo API key trên cổng lập trình viên Baichuan.',
    seedModels: [
      { modelId: 'Baichuan4', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'paid', priority: 86 },
    ],
  },
  {
    id: '01ai',
    name: '01.AI (Yi)',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.lingyiwanwu.com/v1',
    apiKeyUrl: 'https://platform.lingyiwanwu.com/apikeys',
    website: 'https://01.ai',
    category: 'commercial',
    descriptionEn: 'Yi-Lightning and Yi-Large high-performance bilingual LLMs.',
    descriptionVi: 'Các mô hình Yi-Lightning và Yi-Large với hiệu năng tính toán cao.',
    keyInstructionsEn: 'Register on 01.AI platform and generate an API key.',
    keyInstructionsVi: 'Đăng ký tại nền tảng 01.AI và tạo API key.',
    seedModels: [
      { modelId: 'yi-lightning', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'paid', priority: 89 },
    ],
  },
  {
    id: 'stepfun',
    name: 'StepFun',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.stepfun.com/v1',
    apiKeyUrl: 'https://platform.stepfun.com/interface-key',
    website: 'https://stepfun.com',
    category: 'commercial',
    descriptionEn: 'Step-2 trillion-parameter MoE and Step-1V multimodal models.',
    descriptionVi: 'Mô hình Step-2 kiến trúc MoE hàng nghìn tỷ tham số và Step-1V đa phương tiện.',
    keyInstructionsEn: 'Create an API key in StepFun developer platform.',
    keyInstructionsVi: 'Tạo API key trong nền tảng lập trình viên StepFun.',
    seedModels: [
      { modelId: 'step-2-16k', capabilities: ['chat', 'streaming'], freeTier: 'paid', priority: 87 },
    ],
  },
  {
    id: 'replicate',
    name: 'Replicate',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.replicate.com/v1',
    apiKeyUrl: 'https://replicate.com/account/api-tokens',
    website: 'https://replicate.com',
    category: 'commercial',
    descriptionEn: 'Run thousands of open-source models with cloud API endpoints.',
    descriptionVi: 'Chạy hàng ngàn mô hình mã nguồn mở trên nền tảng đám mây.',
    keyInstructionsEn: 'Copy API token from Replicate account settings.',
    keyInstructionsVi: 'Sao chép API token trong trang cài đặt tài khoản Replicate.',
    seedModels: [
      { modelId: 'meta/meta-llama-3.1-405b-instruct', capabilities: ['chat', 'streaming'], freeTier: 'paid', priority: 90 },
    ],
  },
  {
    id: 'ai21',
    name: 'AI21 Labs',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.ai21.com/studio/v1',
    apiKeyUrl: 'https://studio.ai21.com/account/api-key',
    website: 'https://ai21.com',
    category: 'commercial',
    descriptionEn: 'Jamba 1.5 Large and Mini Mamba-Transformer hybrid models.',
    descriptionVi: 'Mô hình Jamba 1.5 kết hợp kiến trúc Mamba và Transformer tốc độ cao.',
    keyInstructionsEn: 'Generate an API key in AI21 Studio.',
    keyInstructionsVi: 'Tạo API key trong AI21 Studio.',
    seedModels: [
      { modelId: 'jamba-1.5-large', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'paid', priority: 88 },
    ],
  },
  {
    id: 'azure-openai',
    name: 'Azure OpenAI Service',
    adapterType: 'openai-compatible',
    baseUrl: 'https://{resource-name}.openai.azure.com/openai/deployments/{deployment-id}',
    apiKeyUrl: 'https://portal.azure.com',
    website: 'https://azure.microsoft.com',
    category: 'commercial',
    descriptionEn: 'Enterprise OpenAI models hosted inside Microsoft Azure security boundary.',
    descriptionVi: 'Các mô hình OpenAI dành cho doanh nghiệp trong hạ tầng bảo mật Microsoft Azure.',
    keyInstructionsEn: 'Obtain endpoint and API key from your Azure OpenAI resource.',
    keyInstructionsVi: 'Lấy endpoint và API key từ tài nguyên Azure OpenAI trong Azure Portal.',
    seedModels: [
      { modelId: 'azure-gpt-4o', capabilities: ['chat', 'streaming', 'tools', 'vision'], freeTier: 'paid', priority: 94 },
    ],
  },
  {
    id: 'aws-bedrock',
    name: 'AWS Bedrock Gateway',
    adapterType: 'openai-compatible',
    baseUrl: 'https://bedrock-runtime.{region}.amazonaws.com',
    apiKeyUrl: 'https://aws.amazon.com/bedrock',
    website: 'https://aws.amazon.com/bedrock',
    category: 'commercial',
    descriptionEn: 'Amazon Bedrock serverless foundation models (Claude, Llama, Titan).',
    descriptionVi: 'Hạ tầng Amazon Bedrock với Claude, Llama và Titan tích hợp đám mây AWS.',
    keyInstructionsEn: 'Configure AWS credentials or IAM bearer token.',
    keyInstructionsVi: 'Cấu hình AWS credentials hoặc token IAM.',
    seedModels: [
      { modelId: 'anthropic.claude-3-5-sonnet', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'paid', priority: 96 },
    ],
  },
  {
    id: 'upstage',
    name: 'Upstage Solar',
    adapterType: 'openai-compatible',
    baseUrl: 'https://api.upstage.ai/v1/solar',
    apiKeyUrl: 'https://console.upstage.ai/api-keys',
    website: 'https://upstage.ai',
    category: 'commercial',
    descriptionEn: 'Solar Pro and Solar Mini models specialized in reasoning and document analysis.',
    descriptionVi: 'Mô hình Solar Pro và Solar Mini chuyên biệt về tư duy và xử lý văn bản.',
    keyInstructionsEn: 'Create key on Upstage console.',
    keyInstructionsVi: 'Tạo API key trên bảng điều khiển Upstage.',
    seedModels: [
      { modelId: 'solar-pro', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'paid', priority: 87 },
    ],
  },
  {
    id: 'aihubmix',
    name: 'AiHubMix Gateway',
    adapterType: 'openai-compatible',
    baseUrl: 'https://aihubmix.com/v1',
    apiKeyUrl: 'https://aihubmix.com',
    website: 'https://aihubmix.com',
    category: 'commercial',
    descriptionEn: 'Universal enterprise API proxy supporting all global models in one balance.',
    descriptionVi: 'Cổng trung chuyển API tích hợp tất cả mô hình thế giới với 1 số dư duy nhất.',
    keyInstructionsEn: 'Sign in to AiHubMix and generate token.',
    keyInstructionsVi: 'Đăng nhập vào AiHubMix và tạo token.',
    seedModels: [
      { modelId: 'claude-3-5-sonnet-20241022', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'paid', priority: 95 },
      { modelId: 'gpt-4o', capabilities: ['chat', 'streaming', 'tools'], freeTier: 'paid', priority: 94 },
    ],
  },
];
